# Generated by Django 3.1.6 on 2021-05-07 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_auto_20210507_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdetailstb',
            old_name='PackegeType',
            new_name='PackageType',
        ),
    ]
