# Generated by Django 3.1.6 on 2021-07-15 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CargoApp', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBranchesTB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BranchName', models.CharField(default='', max_length=100)),
                ('BranchContactnumber', models.CharField(default='', max_length=100)),
                ('BranchEmail', models.EmailField(max_length=254)),
                ('BranchAddress', models.CharField(default='', max_length=100)),
                ('BranchCity', models.CharField(default='', max_length=100)),
                ('BranchState', models.CharField(default='', max_length=100)),
                ('BranchPincode', models.CharField(default='', max_length=100)),
                ('BranchCountry', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRegisterTB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=100)),
                ('Dateofjoin', models.DateField(null=True)),
                ('Age', models.IntegerField(null=True)),
                ('Gender', models.CharField(default='', max_length=100)),
                ('Address', models.CharField(default='', max_length=100)),
                ('City', models.CharField(default='', max_length=100)),
                ('State', models.CharField(default='', max_length=100)),
                ('Country', models.CharField(default='', max_length=100)),
                ('Photo', models.ImageField(default='', upload_to='media/')),
                ('EmailID', models.EmailField(default='', max_length=254)),
                ('Phonenumber', models.CharField(default='', max_length=100)),
                ('Loginname', models.CharField(default='', max_length=100)),
                ('Password', models.CharField(default='', max_length=100)),
                ('ConfirmPassword', models.CharField(default='', max_length=100)),
                ('Status', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationsTB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shippername', models.CharField(default='', max_length=100)),
                ('Description', models.CharField(default='', max_length=100)),
                ('Status', models.CharField(default='', max_length=100)),
                ('DeliveryDate', models.DateField(default='', max_length=100)),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Cargotb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CargoApp.cargotb')),
            ],
        ),
    ]
