# Generated by Django 3.1.6 on 2021-07-15 09:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Origin', models.CharField(default='', max_length=100)),
                ('Shippername', models.CharField(default='', max_length=100)),
                ('OrderDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('ContactNumber', models.CharField(blank=True, default='', max_length=17, validators=[django.core.validators.RegexValidator(message="ContactNumber must be entered in the format:'+999999999'. up to 15 digits allowed", regex='^\\+?1?\\d{9,15}$')])),
                ('Destination', models.CharField(default='', max_length=100)),
                ('DeliveryDate', models.CharField(default='', max_length=100)),
                ('ShipperAddress', models.CharField(default='', max_length=100)),
                ('Recivername', models.CharField(default='', max_length=100)),
                ('ReciverEmail', models.EmailField(max_length=254)),
                ('ReciverContact', models.CharField(default=True, max_length=100)),
                ('ReciverAddresss', models.CharField(default=True, max_length=100)),
                ('ReciverPin', models.IntegerField()),
                ('ReciverDistrict', models.CharField(default=True, max_length=100)),
                ('ReciverState', models.CharField(default=True, max_length=100)),
                ('ReciverCountry', models.CharField(default=True, max_length=100)),
                ('CargoWeigth', models.CharField(default=True, max_length=100)),
                ('CargoQuantity', models.CharField(default=True, max_length=100)),
                ('ShipmentType', models.CharField(default=True, max_length=100)),
                ('NetRate', models.CharField(default=True, max_length=100)),
                ('Type', models.CharField(default=True, max_length=100)),
                ('Status', models.CharField(default=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cargotb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(default='', max_length=100)),
                ('Lastname', models.CharField(default='', max_length=100)),
                ('DateOfBirth', models.CharField(default='', max_length=30)),
                ('Gender', models.CharField(default='', max_length=100)),
                ('Age', models.IntegerField(null=True)),
                ('ContactNumber', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="ContactNumber must be entered in the format:'+999999999'. up to 15 digits allowed", regex='^\\+?1?\\d{9,15}$')])),
                ('Country', models.CharField(default='', max_length=30)),
                ('State', models.CharField(default='', max_length=30)),
                ('District', models.CharField(default='', max_length=100)),
                ('Address', models.CharField(default='', max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Photo', models.ImageField(default='', upload_to='media/')),
                ('Username', models.CharField(default='', max_length=100)),
                ('Password', models.CharField(default='', max_length=8)),
                ('ConfirmPassword', models.CharField(default='', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shippername', models.CharField(default=True, max_length=100)),
                ('Origin', models.CharField(default=True, max_length=100)),
                ('Destination', models.CharField(default=True, max_length=100)),
                ('Type', models.CharField(default=True, max_length=100)),
                ('DeliveryCharge', models.CharField(default=True, max_length=100)),
                ('ReciverAddresss', models.CharField(default=True, max_length=100)),
                ('CargoWeigth', models.CharField(default=True, max_length=100)),
                ('PaymentType', models.CharField(default=True, max_length=100)),
                ('TotalPayment', models.CharField(default=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardholdersName', models.CharField(default=True, max_length=100)),
                ('CardNumber', models.CharField(default=True, max_length=100)),
                ('ExpiryMonth', models.CharField(default=True, max_length=100)),
                ('ExpiryYear', models.CharField(default=True, max_length=100)),
                ('CVV', models.CharField(default=True, max_length=100)),
                ('Amount', models.CharField(default=True, max_length=100)),
                ('Cargotb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CargoApp.cargotb')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shippername', models.CharField(default='', max_length=100)),
                ('Comments', models.CharField(default='', max_length=100)),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CargoApp.bookingtb')),
                ('Cargotb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CargoApp.cargotb')),
            ],
        ),
        migrations.AddField(
            model_name='bookingtb',
            name='Cargotb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CargoApp.cargotb'),
        ),
    ]
